
sccfinder: sccfinder.cpp
	g++ -g -o sccfinder sccfinder.cpp
	#g++ -lrt -o sccfinder sccfinder.cpp

randomgraph: randomgraph.cpp
	g++ -o randomgraph randomgraph.cpp
clean:
	rm -f sccfinder sccfinder.o
	rm -f randomgraph randomgraph.o
