all: sccfinder.cpp randomgraph.cpp randomGraphTest.cpp
	g++ -g -o sccfinder sccfinder.cpp
	g++ -g -o randomgraph randomgraph.cpp
	g++ -g -o randomGraphTest randomGraphTest.cpp

clean:
	rm -f sccfinder sccfinder.o
	rm -f randomgraph randomgraph.o
	rm -f randomGraphTest randomGraphTest.o
