#!/bin/sh

#Compile and clean
make clean
make
make randomgraph

#Run the code


    mkdir ./randomOut
    mkdir ./part2out

for k in {1..8}
do
     mkdir ./randomOut/$k 
     mkdir ./part2out/$k

for j in {1..100}

do
     mkdir ./randomOut/$k/$j 
     mkdir ./part2out/$k/$j
done
done
#value of m
for j in {1..100}
do
#change number of random graphs for each value of m
for i in {0..100}
do 
    
    ./randomgraph 100 `expr 435 + 3 \* $j` ./randomOut/1/$j/$i
    ./sccfinder ./randomOut/1/$j/$i ./part2out/1/$j/$i

    sleep .1 

:<<'END'
    ./randomgraph 1000 `expr 1000 + 999000 \* $`j ./randomOut/2/$j/$i
    ./sccfinder ./randomOut/2/$j/$i ./part2out/2/$j/$i

echo $i
    ./randomgraph 10000 10000+999900*j ./randomOut/3/$j/$i
    ./sccfinder ./randomOut/3/$j/$i ./part2out/3/$j/$i
echo $i
    ./randomgraph 50000 50000+24999500 *j ./randomOut/4/$j/$i
    ./sccfinder ./randomOut/4/$j/$i ./part2out/4/$j/$i
echo $i
    ./randomgraph 100000 100000+99999000*j ./randomOut/5/$j/$i
    ./sccfinder ./randomOut/5/$j/$i ./part2out/5/$j/$i
echo $i
    ./randomgraph 200000 200000+399998000*j ./randomOut/6/$j/$i
    ./sccfinder ./randomOut/6/$j/$i ./part2out/6/$j/$i
echo $i
    ./randomgraph 300000 300000+899997000*j ./randomOut/7/$j/$i
    ./sccfinder ./randomOut/7/$j/$i ./part2out/7/$j/$i
echo $i
    ./randomgraph 500000 500000+2499995000*j ./randomOut/8/$j/$i
    ./sccfinder ./randomOut/8/$j/$i ./part2out/8/$j/$i
END


done

done



